# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

# initialise
fib <- c(1, 2);
fib.limit <- 4000000;
fib.next <- 0;
fib.breach <- fib.limit;

# create a series of fibonacci numbers
while(fib.next < fib.breach){
  n1 <- fib[length(fib) - 1];
  n2 <- fib[length(fib)];
  fib.next <- n2 + n1;
  fib <- c(fib, fib.next);
  fib.breach <- fib.limit - n2;
}

# find the even numbers
fib.even <- fib %% 2;

# add them together
fib.agg <- aggregate(fib, by = list(fib.even), FUN = sum);
sum.evens <- fib.agg[1, 2];
sum.odds <- fib.agg[2, 2];